# Generated by Django 4.1.7 on 2023-04-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0012_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='create_time',
        ),
    ]
