# Generated by Django 4.1.7 on 2023-04-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0013_rename_date_article_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='date',
        ),
    ]
