# Generated by Django 4.1.7 on 2023-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0015_alter_comment_parent_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='title',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
