# Generated by Django 4.1.7 on 2023-04-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0016_like_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='title',
        ),
    ]
