# Generated by Django 4.1.7 on 2023-03-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_profile_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test_field',
        ),
    ]
